@Backend_HostAddress = http://localhost:5182

GET {{Backend_HostAddress}}/test/
Accept: application/json

###
GET {{Backend_HostAddress}}/supplier/
###
GET {{Backend_HostAddress}}/supplier/2

###
POST {{Backend_HostAddress}}/supplier/
Content-Type: application/json

{
  "name" : "Sherwin-Williams México",
  "email" : "info@sherwin.com.mx",
  "phonenumber" : "800-714-6679"
}

###
PUT {{Backend_HostAddress}}/supplier/
Content-Type: application/json

{
  "id" : 2,
  "name" : "Sherwin-Williams México, Nuevo León",
  "email" : "info@sherwin.com.mx",
  "phonenumber" : "800-714-6679"
}

###
DELETE {{Backend_HostAddress}}/supplier/3

###
GET {{Backend_HostAddress}}/product
###
GET {{Backend_HostAddress}}/product/12
###
POST {{Backend_HostAddress}}/product/
Content-Type: application/json

{
  "name" : "Black",
  "code" : "EPG00007",
  "stock" : 10,
  "minimumstock" : 5,
  "supplierid" : 2
}
###
PUT {{Backend_HostAddress}}/product/
Content-Type: application/json

{
  "id" : 12,
  "name" : "Black",
  "code" : "EPG00007",
  "stock" : 4,
  "minimumstock" : 5,
  "supplierid" : 2
}

###
DELETE {{Backend_HostAddress}}/product/10
###
POST {{Backend_HostAddress}}/user/
Content-Type: application/json

{
  "username" : "Black",
  "password" : "1234ert54",
  "role" : "User"
}